# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    inet:
      addresses:
        - 192.168.1.38/24
      nameservers:
        addresses: [1.1.1.1,8.8.8.8]
      routes:
        - to: default
          via: 192.168.1.1
  version: 2
